apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-order-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  VERSION: "1.0"
  ACCOUNT: "aws:908671954593"
  APP_NAME: "go-order.arch-eks-01-02"
  PORT: "7000"
  ENV: "dev"

  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_MAX_CONNECTION: "10"
  CTX_TIMEOUT: "5"

  LOG_LEVEL: "info" #info, error, warning
  OTEL_EXPORTER_OTLP_ENDPOINT: "localhost:4317"

  OTEL_METRICS: "false"
  OTEL_STDOUT_TRACER: "false"
  OTEL_TRACES: "false"

  OTEL_LOGS: "false"
  OTEL_STDOUT_LOG_GROUP: "false"
  LOG_GROUP: "/mnt/c/Eliezer/log/go-order.log"

  NAME_SERVICE_00: "go-cart"
  URL_SERVICE_00: "http://localhost:7001"
  HOST_SERVICE_00: "go-cart"
  CLIENT_HTTP_TIMEOUT_00: "5"

  NAME_SERVICE_01: "go-inventory"
  URL_SERVICE_01: "http://localhost:7000"
  HOST_SERVICE_01: "go-inventory"
  CLIENT_HTTP_TIMEOUT_01: "5"

  NAME_SERVICE_02: "go-clearance"
  URL_SERVICE_02: "http://localhost:7003"
  HOST_SERVICE_02: "go-clearance"
  CLIENT_HTTP_TIMEOUT_02: "5"