apiVersion: v1
kind: Service
metadata:
  name: &app-name svc-go-order
  namespace: test-a
  labels:
    app: *app-name
spec:
  type: ClusterIP
  ports:
  - port: 7004
    targetPort: 7004
    protocol: TCP
    name: http
  selector:
    app: go-order
